services:
  openfga:
    image: openfga/openfga
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
    restart: on-failure
    command: run
    environment:
      - OPENFGA_PLAYGROUND_ENABLED=true
