version: v0.6.0-alpha.1

log:
  level: debug

namespaces:
  location: file:///home/ory/namespaces.keto.ts

dsn: memory

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467
